<a href="https://colab.research.google.com/github/Ajaysahu01/NUMPY/blob/main/project_sales_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
sales = np.random.randint(500,50000,1000)
sales

array([ 7925, 37942, 41933, 27009, 35009,   823, 33179,  9317, 39701,
       12234, 11975, 33369,   980, 16563, 49106, 12445, 29339, 13234,
       24117, 35708,  3474, 28289, 28382,  3575, 46030, 43237,  9263,
       24172, 37022, 31856, 10888, 17062, 44692,  2145, 46732, 18920,
       37308, 19432, 45675, 18138, 25488, 49900, 14828, 12249, 49524,
        7389, 25582, 36263,  4024, 45333, 49776, 47244, 15714, 45650,
       40873, 49680, 29867,  8632,  8534,  2382, 10782,  2736, 26089,
       48958, 11218, 39390, 19670,  6811, 24271, 23407, 14786,  2419,
       45066,  7834, 39375, 47217, 20457, 26232, 39515,  5076, 40605,
       11753, 32671, 10936, 46902, 44036, 33989, 30498,  7190, 36502,
        1938, 34168, 23645, 15345, 26164, 46571,  6346, 45893,  9148,
       24456, 37754, 33657,   775, 46287, 35766, 38310, 37815, 48818,
       18576, 19129, 16237,  2565, 29936, 37605, 35262, 33089, 40143,
        1221, 28703, 32096, 24868, 22169, 45581, 47553, 46591, 42693,
        4136,  9967, 41745, 13446, 19995, 41337,  3661, 37955, 23186,
       34939,  1706, 36721,  2744, 23836, 38351, 21989, 32256, 35946,
        6048, 25301, 19539, 21357, 24166, 30151, 36673, 25315, 28560,
       28182, 29329, 33002,  6290, 25023, 21680,  7371, 21740, 40646,
       17096, 41314,  3151, 10925, 15865, 32805, 29348, 34982, 42186,
       47431,  9058, 14000, 28101, 46211, 20930, 44800, 24478,  2021,
       27693, 29356, 27180, 32942, 28981, 20007, 17292, 25422, 13372,
       38610, 27945, 48131, 27327, 17784, 47117,  7715,  2320,  5353,
       25457, 33705,  7702, 33686, 44147, 31740, 18054,  3257, 18875,
        9601, 17853, 39350, 26978, 25196, 41200, 43194, 20796, 11927,
       30556, 18138,  6715, 34191, 39907, 36108, 26166, 23297,  9734,
       35118, 44232, 14712, 47210, 30272, 16621, 28340, 29927, 37047,
       33637, 33139, 43706, 11074, 15907,  6769, 42235, 25482, 10236,
       27374, 15645,  7523, 12595, 46549, 24747, 12854,  9132, 37889,
       20597, 33150,  4826, 28792, 20213, 20374, 22484, 38168, 22165,
       37451, 30557, 30293, 15536, 36280, 42840, 14163, 36430,  6964,
       44736, 40662, 41214, 28056, 39723, 17688, 49440, 14497, 29045,
       11060, 34887, 21618, 47816, 43223,  4189, 37985, 29085, 15476,
       47909, 46151, 23880, 34015, 19580,  9768, 14120, 25441, 43925,
       40609, 43335, 14555, 21971, 17737, 20909,  3240, 12405, 19148,
       10334, 33355, 13969,  2285, 43506, 27274, 30218, 48064,  9816,
        6689, 31541,  2587, 23737, 41821, 32898, 30846, 48725,  8348,
       32738, 41880, 46570,  4884, 22371, 12435, 16174, 34576, 21983,
       18496,  8951, 17441, 21873,  3771, 32410, 20328, 10243,  8833,
       46239, 13252, 10383, 22167, 12948,  8258, 49257,  1298, 23185,
       25141,  4867, 36244,  8598,  6510, 32430,  5209, 44609, 35489,
        4563, 43046,  2365,  3071, 15907, 12467, 13403, 35888,  7737,
        6157, 19059, 25742, 44916, 15664,  4424, 23504,  6749,  5632,
       18337, 45208,  7062, 33838,  7243, 39649,  8202, 40979, 16493,
       21636, 48294, 23626, 39980, 38687, 47728, 15206,  5549, 34561,
       31637, 13359, 44060, 26803, 14951, 46048, 38832,  2661, 17999,
       40332, 13883, 47554, 31752, 38248, 49621, 43927, 25771, 40975,
        1839,  5021, 24888,  3593, 23662, 39001, 34211,  9417, 27529,
       45823, 41545, 35198, 37588, 13044, 46129, 28943,  3782, 47230,
       45965, 38116, 12062, 23538, 41615, 35376, 40117, 16674,   918,
        8774, 15412, 23086, 23916, 21642, 25637,  5390,  4143, 22749,
       31084, 20200, 41684,  5329, 14703,  8260,  8002, 45898, 16497,
       24996, 37161, 39232,  3539, 13567, 12368, 19648, 46377,  9877,
       39875, 20435, 18680, 18764,  1491, 25434, 41408, 44827,  5459,
       11396, 30505, 46672, 11068, 35618, 14251, 34087,  9248, 13346,
       31864, 49113,  1183, 11668,  9651, 16741,  7267, 12294, 28267,
       40987, 35413, 42253, 48177, 41509, 45863, 30380, 39506, 10062,
        2388, 15584, 15116, 38593, 19340, 35176, 39751, 44774, 44531,
       15897, 43368, 34856, 40800, 11879, 27336, 46473, 31896,  8884,
        7541,  9210,  9716, 29592, 47771, 46516, 42888, 27831, 31101,
       42212, 23396,  5548, 16003, 22065, 32109, 37163, 29565, 10746,
       14079, 43841, 29984, 48781, 25453,  3054, 16957, 38944, 49046,
       47258, 36943, 15080,  5855,  7543, 29847, 47595, 37772, 24663,
       24855, 11397, 16752, 49092, 41913, 37064, 43695,  3481, 40605,
       31697, 30946, 44525, 13082,  6379, 14815, 16340, 44453, 47832,
       14339, 43655, 48723,  5003,  1137, 15907, 19600, 39983, 13897,
        6677,  8611, 26641, 35746,  6836, 23159, 17408, 37062, 36062,
        9463, 16899,   757, 13782, 15958, 28035,  1478, 41162,  2393,
        6107, 43293, 39335, 18193, 43648,  8250, 28118,  9880, 38426,
       12806, 12850, 15573, 24919, 25369, 23022, 14507, 41426, 44559,
        8370, 36700, 48669, 48337, 10355,  5450, 41701, 39403, 13981,
       12742, 12322, 43479, 10759, 15380, 40747,  9462, 18798, 42496,
       29460, 41733, 32875, 30530, 22108, 13313, 44750, 19508, 21951,
        5394, 48007, 48869, 25532, 11300, 16097,  8011, 45363, 37891,
       27567, 46297,  8429,  9647,  5331, 35343, 34821, 41877, 25158,
       22670, 11781, 11193, 27937, 48841, 22777, 42973, 16945, 43547,
       45445,  1292,  9981, 38248, 48980, 19870, 33565, 38809, 46376,
        1123,  9722, 38128,  3977, 43691, 27139, 18463, 42100, 43686,
       37390, 22368, 30156, 23772, 23125,  6882, 31937, 14194,  9287,
        9994, 14299, 36225, 21427, 38176, 45494,  1158,  6689,  7114,
       46936, 10304, 38937, 22091, 25470,  2406, 37971, 42979, 37120,
       32725, 15774, 40526, 27396, 28311, 24598,  7552, 39979, 44294,
       11932,  8503, 32953, 23649, 21114, 35797, 39586, 24677, 44579,
        1667, 12750,  6847, 14032, 41315, 23588, 17858,  4390,  2771,
       30747, 34122, 11381,  5922,  4223, 42702,  3293, 48046, 35258,
       46818,  7784,  6599, 23992, 45152, 46729, 22322, 17128, 23804,
       32445, 39294,  7748,  4047, 47974,  1182, 26300,  5429,  1634,
       22698, 37717,  1807, 24315, 20201, 32232, 34048, 44987, 36866,
       26011,  6140, 30392, 37859, 44922, 24321, 23575, 11184, 15725,
         639, 39731,  1268,  8553, 28593, 15957,  8165,  9958, 17653,
       41996, 35650, 37242, 29997, 27197, 13680,  3583,  2725,  9741,
       18221, 15089, 42485, 41226, 45312, 37322, 36111, 18074, 33835,
         928, 43491,  9668, 49157,  1578, 23560, 35306, 31804, 40576,
       15301, 39078, 30445, 15010, 19020,  6934, 24998, 39357, 22129,
        5651,  8968,  6885, 23433,  4353, 25075, 12527, 13165, 27619,
       14591, 12818, 15007,  9227, 18747, 41538,  8001, 31464, 38672,
       16070, 44724, 39234, 13342,  4887, 15934, 15659, 47931, 30966,
       13199, 39685,  6771, 49887, 27042, 24481, 36791, 42027, 37325,
       25291, 42402, 12307, 13054, 10245,  2204, 16782, 22452,  1580,
       47865, 36280, 24865,  1188, 11626, 35914, 48461, 30055, 34198,
       12399, 49438, 19773,  5096,  2957,  5910, 41425, 20408, 23793,
        3605, 40312, 15030,  2729, 49383, 48507, 21835, 27337, 47651,
       17897, 46478, 24389,  8248, 27679, 22022, 12462, 37644, 45213,
       47617, 37866, 29056, 48783, 42681, 22001, 11253, 39995, 40770,
       41877, 22899, 26205, 33972, 38667,  7016, 36742, 44933, 42666,
       41778, 14237, 32052, 48763, 44848,  9042, 19904,  5367, 29900,
       19950, 15912, 28084,  1949, 17864, 27658, 37580, 48860, 18933,
       43611,  9523,  1785, 42696, 33635, 28831, 23309,  8741, 31292,
       10862, 35032, 42607, 10218,  2974, 38267, 28212, 10076, 19141,
       12663, 28019, 15624, 19882, 11113, 39145,  3526, 11302, 32592,
       45378,  4153, 42355,  6099, 41708,   641, 25642, 23116,  7417,
       43473, 11766, 29396, 21931, 39086, 23446, 29876, 35343, 37647,
       20090])

In [ ]:
sales= pd.Series(sales)

In [ ]:
sales

0       7925
1      37942
2      41933
3      27009
4      35009
       ...
995    23446
996    29876
997    35343
998    37647
999    20090
Length: 1000, dtype: int64

In [ ]:
sales.size

1000

In [ ]:
sales.shape

(1000,)

In [ ]:
sales.ndim

1

In [ ]:
sales.count()

np.int64(1000)

In [ ]:
sales.index

RangeIndex(start=0, stop=1000, step=1)

In [ ]:
sales.isnull().sum()

np.int64(0)

In [ ]:
#total sales
sales.sum()

np.int64(25202560)

In [ ]:
#average sale
sales.mean()

np.float64(25202.56)

In [ ]:
#highest sales amount
sales.max()

49900

In [ ]:
#lowest sales amount
sales.min()

639

In [ ]:
#top 10 highest sales
sales.nlargest(10)

41     49900
867    49887
50     49776
55     49680
410    49621
44     49524
276    49440
892    49438
904    49383
348    49257
dtype: int64

In [ ]:
#10 lowest sales
sales.nsmallest(10)

792     639
986     641
596     757
102     775
5       823
440     918
819     928
12      980
684    1123
580    1137
dtype: int64

In [23]:
#sales greater than 10000
sales[sales>10000]

1      37942
2      41933
3      27009
4      35009
6      33179
       ...
995    23446
996    29876
997    35343
998    37647
999    20090
Length: 797, dtype: int64

In [24]:
sales[sales>10000].count()

np.int64(797)

In [25]:
#sales between 5000 and 20000
sales[(sales>5000) & (sales<20000)]

9      12234
10     11975
13     16563
15     12445
17     13234
       ...
974    15624
975    19882
976    11113
979    11302
991    11766
Length: 202, dtype: int64

In [26]:
sales[(sales>5000) & (sales<20000)].count()

np.int64(202)

In [28]:
#sales in ascending and descending order
sales.sort_values()

503    10062
970    10076
966    10218
242    10236
340    10243
       ...
410    49621
55     49680
50     49776
867    49887
41     49900
Length: 797, dtype: int64

In [30]:
sales.sort_values(ascending=False)

41     49900
867    49887
50     49776
55     49680
410    49621
       ...
340    10243
242    10236
966    10218
970    10076
503    10062
Length: 797, dtype: int64

In [33]:
#index of highest sale
sales.nlargest(1).index

Index([41], dtype='int64')

In [34]:
#index of lowest sale
sales.nsmallest(1).index

Index([503], dtype='int64')

In [35]:
#total sales value after giving 10% discount
sales.sum()*.90

np.float64(21663804.6)